name: fangscan_mobile
description: Mobile version of FangScan Web Reconnaissance Tool
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^0.13.5
  google_fonts: ^4.0.3
  share_plus: ^6.3.1
  flutter_secure_storage: ^8.0.0
  path_provider: ^2.0.15
  provider: ^6.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true 